version: "3.8"
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conversorcsv-mongodb
    ports:
      - "27017:27020"
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - conversorcsv-network

networks:
  conversorcsv-network:
    driver: bridge
